import { createThemes } from "$lib";

createThemes({
  themes: {
    default: () => import("./themes/default.css?inline"),
    "amber-minimal": () => import("./themes/amber-minimal.css?inline"),
    "amethyst-haze": () => import("./themes/amethyst-haze.css?inline"),
    "bold-tech": () => import("./themes/bold-tech.css?inline"),
    bubblegum: () => import("./themes/bubblegum.css?inline"),
    caffeine: () => import("./themes/caffeine.css?inline"),
    candyland: () => import("./themes/candyland.css?inline"),
    catppuccin: () => import("./themes/catppuccin.css?inline"),
    claude: () => import("./themes/claude.css?inline"),
    claymorphism: () => import("./themes/claymorphism.css?inline"),
    "clean-slate": () => import("./themes/clean-slate.css?inline"),
    "cosmic-night": () => import("./themes/cosmic-night.css?inline"),
    cyberpunk: () => import("./themes/cyberpunk.css?inline"),
    darkmatter: () => import("./themes/darkmatter.css?inline"),
    "doom-64": () => import("./themes/doom-64.css?inline"),
    "elegant-luxury": () => import("./themes/elegant-luxury.css?inline"),
    graphite: () => import("./themes/graphite.css?inline"),
    "kodama-grove": () => import("./themes/kodama-grove.css?inline"),
    "midnight-bloom": () => import("./themes/midnight-bloom.css?inline"),
    "mocha-mousse": () => import("./themes/mocha-mousse.css?inline"),
    "modern-minimal": () => import("./themes/modern-minimal.css?inline"),
    mono: () => import("./themes/mono.css?inline"),
    nature: () => import("./themes/nature.css?inline"),
    "neo-brutalism": () => import("./themes/neo-brutalism.css?inline"),
    notebook: () => import("./themes/notebook.css?inline"),
    "northern-lights": () => import("./themes/northern-lights.css?inline"),
    "ocean-breeze": () => import("./themes/ocean-breeze.css?inline"),
    "pastel-dreams": () => import("./themes/pastel-dreams.css?inline"),
    perpetuity: () => import("./themes/perpetuity.css?inline"),
    "quantum-rose": () => import("./themes/quantum-rose.css?inline"),
    "retro-arcade": () => import("./themes/retro-arcade.css?inline"),
    "sage-garden": () => import("./themes/sage-garden.css?inline"),
    "soft-pop": () => import("./themes/soft-pop.css?inline"),
    "solar-dusk": () => import("./themes/solar-dusk.css?inline"),
    "starry-night": () => import("./themes/starry-night.css?inline"),
    supabase: () => import("./themes/supabase.css?inline"),
    "sunset-horizon": () => import("./themes/sunset-horizon.css?inline"),
    "t3-chat": () => import("./themes/t3-chat.css?inline"),
    tangerine: () => import("./themes/tangerine.css?inline"),
    twitter: () => import("./themes/twitter.css?inline"),
    vercel: () => import("./themes/vercel.css?inline"),
    "vintage-paper": () => import("./themes/vintage-paper.css?inline"),
    "violet-bloom": () => import("./themes/violet-bloom.css?inline"),
  },
  defaultTheme: "default",
  defaultScheme: "system",
});
